customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [

        path('dashboard/', views.dashboard, name='dashboard'),
        path('customers/', views.CustomersList.as_view(), name='customers'),
        path('customer/create/', views.CustomerCreate.as_view(), name='customer_create'),
        path('customer/update/<int:pk>', views.CustomerUpdate.as_view(), name='customer_update'),

        path('items/', views.ItemsList.as_view(), name='items_list'),
        path('items/<int:pk>', views.ItemsDetail.as_view(), name='items_details'),
        path('item/create/', views.ItemCreate.as_view(), name='item_create'),
        path('item/update/<int:pk>', views.ItemUpdate.as_view(), name='item_update'),


        path('item/price/', views.get_item_price, name='items_price'),


        path('orders/', views.OrderList.as_view(), name='orders'),
        path('orders/<int:pk>', views.OrderDetail.as_view(), name='order_details'),

        path('order/create/', views.OrderCreate.as_view(), name='order_create'),
        path('order/update/<int:order_id>', views.order_update, name='order_update'),
        path('order/delete/<int:pk>', views.OrderDelete.as_view(), name='order_delete'),

]

jarwell/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('customers.urls')),
]

customers/models.py
from django.db import models
import computed_property



class Customer(models.Model):
   
    first_name = models.CharField(max_length=75)
    last_name = models.CharField(max_length=75)
    address = models.CharField(max_length=150)
    contact = models.CharField(max_length=75)
    date_encoded = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name.title() +" "+ self.last_name.title()

class Item(models.Model):
    
    name = models.CharField(max_length=75)
    size = models.CharField(max_length=20, default='small')
    price = models.FloatField(default=0)
    date_encoded = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name.title() +" "+ self.size.upper() +" (price : "+str(self.price)+")"

class Order(models.Model):

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    shipping_fee = models.DecimalField(max_digits=7, decimal_places=2)
    payment_status = models.IntegerField(default=0)
    shipping_status = models.BooleanField(default=False)
    notes = models.TextField(default="None")
    date = models.DateField(auto_now_add=True)

    @property
    def total_order(self):
        order_items = OrderItem.objects.filter(order_id=self.id)
        sum = 0
        for order_item in order_items:
            sum = sum + order_item.price
        return ( sum + float(self.shipping_fee) )


    @property
    def total_qty(self):
        order_items = OrderItem.objects.filter(order_id=self.id)
        total_qty = 0
        for order_item in order_items:
            total_qty = (order_item.qty + total_qty)
        return total_qty


    def __str__(self):
        return self.customer.first_name.title() +" "+self.customer.last_name.title()

class OrderItem(models.Model):

    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)
    #bulk_price = computed_property.ComputedDecimalField(max_digits=7, decimal_places=2, compute_from='price')

    @property
    def price(self):
         return self.qty * self.item.price


    def __str__(self):
        return self.item.name +" "+ str(self.qty)

customers/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory
from .models import Customer, Item, Order, OrderItem


class  DateInput(forms.DateInput):
    input_type = 'date'

class CustomerForm(ModelForm):

    class Meta:
        model = Customer    
        #fields = ['name', 'description', 'price']
        fields = '__all__'

class ItemForm(ModelForm):

    class Meta:
        model = Item
        fields = '__all__'
        size_choices = [('extra small', 'extra small'),
                ('small', 'small'), 
                ('medium', 'medium'),
                ('large', 'large'),
                ('extra large', 'extra large'),
                ]
        widgets = {'size': forms.Select(choices=size_choices)}

class OrderForm(ModelForm):    
    class Meta:
        model = Order
        fields = '__all__'


class OrderItemForm(ModelForm):

    class Meta:
        model = OrderItem
        fields = ['item', 'qty']


OrderItemFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm)

customers/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy

#views
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


#models
from .models import Customer, Item, Order, OrderItem

#forms
from .forms import CustomerForm, ItemForm, OrderForm, \
        OrderItemFormset 

#decorator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Customer, Item, Order

#formset
from django.forms import inlineformset_factory
#atomic
from django.db import transaction

@login_required(login_url='/accounts/login')
def dashboard(request):

    customer_count = Customer.objects.all().count()
    item_count = Item.objects.all().count()
    order_count = Order.objects.all().count()

    new_customers = Customer.objects.order_by('-date_encoded')[:5]

    context = {'customer_count' : customer_count,
            'item_count' : item_count,
            'order_count' : order_count,
            'new_customers' : new_customers,
            }

    return render(request, 'customers/index.html', context )


@method_decorator(login_required, name='dispatch')
class CustomersList(ListView):
    template_name = 'customers/customers.html'
    context_object_name = 'customers'

    def get_queryset(self):
        return Customer.objects.order_by('-date_encoded')

@method_decorator(login_required, name='dispatch')
class CustomerCreate(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_create.html'
    success_url = reverse_lazy('customers:customers')

@method_decorator(login_required, name='dispatch')
class CustomerUpdate(SuccessMessageMixin, UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/customer_update.html'
    success_url = reverse_lazy('customers:customers')
    #success_url = HttpResponseRedirect(self.request.path_info)
    success_message = 'Customer successfully saved!'


@method_decorator(login_required, name='dispatch')
class ItemsList(ListView):
    template_name = 'customers/items.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Item.objects.order_by('-date_encoded')


class ItemsDetail(DetailView):
    model = Item
    template_name = 'customers/item_details.html'


@method_decorator(login_required, name='dispatch')
class ItemCreate(CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'customers/item_create.html'
    success_url = reverse_lazy('customers:items_list')


@method_decorator(login_required, name='dispatch')
class ItemUpdate(UpdateView):
    model = Item
    form_class = ItemForm
    template_name = 'customers/item_create.html'
    success_url = reverse_lazy('customers:items_list')


@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    template_name = 'customers/orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.order_by('-date')


class OrderDetail(DetailView):
    model = Order
    template_name = 'customers/order_details.html'





@method_decorator(login_required, name='dispatch')
class OrderCreate(CreateView):
    model = Order
    fields = ['customer', 'shipping_fee', 'shipping_status', 'notes']
    template_name = 'customers/order_create.html'
    success_url = reverse_lazy('customers:orders')

    def get_context_data(self, **kwargs):
        data = super(OrderCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['items'] = OrderItemFormset(self.request.POST)
        else:
            data['items'] = OrderItemFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        items = context['items']
        with transaction.atomic():
            self.object = form.save()

            if items.is_valid():
                items.instance = self.object
                items.save()

        return super(OrderCreate, self).form_valid(form)



class OrderDelete(DeleteView):
    model = Order
    fields = ['customer']
    success_url = reverse_lazy('customers:orders')



def order_update(request, order_id):

    order = Order.objects.get(id=order_id)
    form = OrderForm(request.POST, instance=order)
    ItemFormset = inlineformset_factory(Order, OrderItem, form=OrderForm, extra=1)

    if request.method == 'POST':

        formset = ItemFormset(request.POST, instance=order)

        if formset.is_valid():
            form.save()
            formset.save()
            from django.contrib import messages
            messages.success(request, 'Order successfully updated')
    else:

        form = OrderForm(instance=order)
        formset = ItemFormset(instance=order)

    return render(request, 'customers/order_update.html', {'form':form, 'formset' : formset})



@login_required(login_url='/accounts/login')
def get_item_price(request):

        item_id = request.GET['item_id']
        qty = request.GET['qty']
        shipping_fee = request.GET['shipping_fee']

        item = Item.objects.get(pk=item_id)

        total_price = ( (item.price * float(qty) ) + float(shipping_fee) )
        return JsonResponse(total_price, safe=False)








#def get_item(request):
    

customers/templates/customers/customer_create.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						Create New Customer
					</div>
					<div class='card-body'>	

						<div id='email_exist'> </div>

						<form method='post'>
						{% csrf_token %}

							{{ form | crispy }}

							<p><input type='submit' value='Save' class='btn btn-success'></p>
						</form>	
					</div>
				</div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
<script>
/*$('#generate_password').on('click', function() {

	$.ajax({
		url : '/dashboard/users/create/generate_password/',
		success: function(password) {
			
			$('#password').val(password)
		}
	})

});*/</script>
{% endblock %}

customers/templates/customers/customer_update.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						Update Customer
					</div>
					<div class='card-body'>	

						<div id='email_exist'> </div>

						<form method='post'>
						{% csrf_token %}

							{{ form | crispy }}

							<p><input type='submit' value='Save' class='btn btn-success'></p>
						</form>	
					</div>
				</div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
<script>
/*$('#generate_password').on('click', function() {

	$.ajax({
		url : '/dashboard/users/create/generate_password/',
		success: function(password) {
			
			$('#password').val(password)
		}
	})

});*/</script>
{% endblock %}

customers/templates/customers/customers.html
{% extends 'customers/base.html' %}

{% block content %}
<div class="content-wrap">
	<div class='main'>
	    <div class="page-header">
		<div class="page-title">
			<h1> Customers </h1>
		</div>
	    </div>

		<div class='containera-fluid'>
			<section id='main-content'>

				<div class='card'>
					<div class='card-body'>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}						<div class='table-responsive'>

							<p>
							<a href='{% url "customers:customer_create" %}'>
							<input type='button' id='checkout_btn' value='Create New Customer' />
							</a>
							</p>

							<table class='table table-hover' id='myTable'>
								<thead>
									<tr>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Address</th>
										<th>Contact</th>
										<th></th>

									</tr>	
								</thead>
								<tbody> 
									{% for customer in customers %}
									<tr>
										<td>{{ customer.first_name | title }}</td>
										<td>{{ customer.last_name | title }}</td>
										<td>{{ customer.address | slice:":15" }} ...</td>
										<td>{{ customer.contact }}</td>
										<td>
											<a href='{% url "customers:customer_update" customer.id %}'>
											<i class='ti-pencil'></i>
											</a>
										</td>

									</tr>
									{% endfor %}
								
								</tbody>

							</table>


						</div>	
					</div>
				</div>

			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->

{% endblock content %}

customers/templates/customers/index.html
{% extends 'customers/base.html' %}
{% block content %}



        <div class="content-wrap">
            <div class="main">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-8 p-r-0 title-margin-right">
                            <div class="page-header">
                                <div class="page-title">
					<h1>Hello, <span>Welcome {{user.username | title}} </span></h1>
                                </div>
                            </div>
                        </div>
                        <!-- /# column -->
                        <div class="col-lg-4 p-l-0 title-margin-left">
                            <div class="page-header">
                                <div class="page-title">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                        <li class="breadcrumb-item active">Home</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                        <!-- /# column -->
                    </div>
                    <!-- /# row -->
                    <section id="main-content">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="stat-widget-two">
                                        <div class="stat-content">
						<a href='{% url "customers:customers" %}'>
						<div class="stat-text"><i class='ti-user' style='color: orange'></i>Customers</div>	
						<div class="stat-digit">{{ customer_count }}</div>
						</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="stat-widget-two">
                                        <div class="stat-content">
						<a href='{% url "customers:orders" %}'>
						<div class="stat-text"><i class='ti-shopping-cart' style='color:orange'></i>Orders</div>
						<div class="stat-digit"> {{ order_count }}</div>
						</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="stat-widget-two">
                                        <div class="stat-content">
						<a href='{% url "customers:items_list" %}'>
						<div class="stat-text"><i class='ti-package' style='color:orange'></i>Items</div>
						<div class="stat-digit">{{ item_count }}</div>
						</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- /# card -->
                            </div>
                            <!-- /# column -->
                        </div>
                        <!-- /# row -->


<!--                        <div class="row"></div>

                        <div class="row"></div>


                        <div class="row"></div>




                        <div class="row">
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="card-title">
                                        <h4>Task</h4>
                                    </div>
                                    <div class="todo-list">
                                        <div class="tdl-holder">
                                            <div class="tdl-content">
                                                <ul>
                                                    <li>
                                                        <label>
                                                        <input type="checkbox"><i></i><span>Post three to six times on Twitter.</span>
                                                        <a href='#' class="ti-close"></a>
                                                    </label>
                                                    </li>
                                                    <li>
                                                        <label>
                                                        <input type="checkbox" checked><i></i><span>Post one to two times on Facebook.</span>
                                                        <a href='#' class="ti-close"></a>
                                                    </label>
                                                    </li>
                                                    <li>
                                                        <label>
                                                        <input type="checkbox" checked><i></i><span>Follow back those who follow you</span>
                                                        <a href='#' class="ti-close"></a>
                                                    </label>
                                                    </li>
                                                    <li>
                                                        <label>
                                                        <input type="checkbox" checked><i></i><span>Connect with one new person</span>
                                                        <a href='#' class="ti-close"></a>
                                                    </label>
                                                    </li>
                                                </ul>
                                            </div>
                                            <input type="text" class="tdl-new form-control" placeholder="Write new item and hit 'Enter'...">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card alert">
                                    <div class="card-title">
                                        <h4>Web Server</h4>
                                    </div>
                                    <div class="cpu-load-chart">
                                        <div id="cpu-load" class="cpu-load"></div>
                                    </div>
                                </div>
                                <!-- /# card -->
                            </div>
			
                            <!-- /# column -->
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="card-title">
                                        <h4>New Customers</h4>

                                    </div>
				     {% for new_customer in new_customers %}
                                    <div class="recent-comment">
                                        <div class="media">
                                            <div class="media-left">
                                            </div>
                                            <div class="media-body">
						    <a href='#'>
						    <h4 class="media-heading">{{new_customer.first_name | title }}</h4>
						    </a>
						    <p></p>
						    <p style='color:red'>Contact: {{ new_customer.contact }}</p>
                                                <div class="comment-action">
                                                    <div class="badge badge-success">New</div>
                                                    <span class="m-l-10">
													<a href="#"><i class="ti-check color-success"></i></a>
													<a href="#"><i class="ti-close color-danger"></i></a>
													<a href="#"><i class="fa fa-reply color-primary"></i></a>
												</span>
                                                </div>
						<p class="comment-date">{{new_customer.date_encoded}}</p>
                                            </div>
                                        </div>
					{% endfor %}
                                    </div>
                                </div>
                                <!-- /# card -->
                            </div>
                        </div>





                        <div class="row">
                            <div class="col-lg-12">
                                <div class="footer">
                                    <p>2018 © Admin Board. - <a href="#">example.com</a></p>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>





{% endblock content %}

customers/templates/customers/item_create.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						New Items
					</div>
					<div class='card-body'>	

						<div id='email_exist'> </div>

						<form method='post'>
						{% csrf_token %}

							{{ form | crispy }}

							<p><input type='submit' value='Save' class='btn btn-success'></p>
						</form>	
					</div>
				</div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
<script>
/*$('#generate_password').on('click', function() {

	$.ajax({
		url : '/dashboard/users/create/generate_password/',
		success: function(password) {
			
			$('#password').val(password)
		}
	})

});*/</script>
{% endblock %}

customers/templates/customers/item_details.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% load humanize %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						Item Dtails
					</div>
					<div class='card-body'>
						<ul>
							<li> {{ item.name }} </a>
							<li> {{ item.size }} </a>
							<li> {{ item.price }} </a>
						</ul>
					</div>
				</div>

				<div class='card'></div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
{% endblock %}

customers/templates/customers/items.html
{% extends 'customers/base.html' %}

{% block content %}
<div class="content-wrap">
	<div class='main'>
	    <div class="page-header">
		<div class="page-title">
			<h1> Customers </h1>
		</div>
	    </div>

		<div class='containera-fluid'>
			<section id='main-content'>

				<div class='card'>
					<div class='card-body'>
						<div class='table-responsive'>

							<p>
							<a href='{% url "customers:item_create" %}'>
							<input type='button' id='checkout_btn' value='Create New Item' />
							</a>
							</p>

							<table class='table table-hover' id='myTable'>
								<thead>
									<tr>
										<th>Item Name</th>
										<th>Sizes</th>
										<th>Price</th>
										<th></th>

									</tr>	
								</thead>
								<tbody> 
									{% for item in items %}
									<tr>
										<td>
											<a href='{% url "customers:items_details" item.id %}'>
											{{ item.name | title }}
											</a>
										</td>
										<td>{{ item.size | title }}</td>
										<td> PHP {{ item.price }}</td>
										<td>
											<a href='{% url "customers:item_update" item.id %}'>
											<i class='ti-pencil'></i>
											</a>
										</td>

									</tr>
									{% endfor %}
								
								</tbody>

							</table>


						</div>	
					</div>
				</div>

			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->

{% endblock content %}

customers/templates/customers/order_confirm_delete.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% load humanize %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						Orders
					</div>
					<div class='card-body'>
						<p>
						<form method='post'>
							{% csrf_token %}
							Are you sure you want to delete this order ?	
							<input type='submit' class='btn btn-success' value='Yes'>
						</form>
							<a href ='{% url "customers:order_details" order.id %}'> No </a>
						</p>

						<ul>
							<li> <p> {{ order.customer }} </p> </li>
							<li> <p> Ordered last: {{ order.date }} </p> </li>
							<li> <p> <label> Shipped to: </label>  {{ order.customer.address }} </p> </li>
							<li> <p> <label> Quantity: </label>  {{ order.total_qty }} </p> </li>
							<li> <p> <label> Shipping fee: </label> PHP {{ order.shipping_fee }} </p> </li>
							<li> <p> <label> Total Order Price: </label> <b> PHP {{ order.total_order | intcomma }} </b> </p> </li>
						</li>

					</div>
				</div>

				<div class='card'>
					<div class='table-responsive'>
					<table class='table table-hover' id='myTable'>
						<thead>
							<tr>
								<th>Item</th>
								<th>Qty</th>
								<th>Price</th>
							</tr>	
						</thead>
						<tbody> 

					{% for orderitem in order.orderitem_set.all %}	
							<tr>
								<td>{{ orderitem.item }}</td>
								<td>{{ orderitem.qty }} dozens</td>
								<td>PHP {{ orderitem.price | intcomma }}</td>
							</tr>
						{% endfor %}
						
						</tbody>

					</table>
					</div>


				</div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
{% endblock %}

customers/templates/customers/order_details.html
{% extends 'customers/base.html' %}

{% load crispy_forms_tags  %}
{% load humanize %}
{% block content %}
<div class="content-wrap">
	<div class='main'>
		<div class='containera-fluid'>
			<section id='main-content'>
				<div class='card'>


					<div class='card-title'>
						Orders
					</div>
					<div class='card-body'>

						<ul>
							<li> <p> {{ order.customer }} </p> </li>
							<li> <p> Ordered last: {{ order.date }} </p> </li>
							<li> <p> <label> Shipped to: </label>  {{ order.customer.address }} </p> </li>
							<li> <p> <label> Quantity: </label>  {{ order.total_qty }} </p> </li>
							<li> <p> <label> Shipping fee: </label> PHP {{ order.shipping_fee }} </p> </li>
							<li> <p> <label> Total Order Price: </label> <b> PHP {{ order.total_order | intcomma }} </b> </p> </li>
						</li>

					</div>
				</div>

				<div class='card'>
					<div class='table-responsive'>
					<table class='table table-hover' id='myTable'>
						<thead>
							<tr>
								<th>Item</th>
								<th>Qty</th>
								<th>Price</th>
							</tr>	
						</thead>
						<tbody> 

					{% for orderitem in order.orderitem_set.all %}	
							<tr>
								<td>{{ orderitem.item }}</td>
								<td>{{ orderitem.qty }} dozens</td>
								<td>PHP {{ orderitem.price | intcomma }}</td>
							</tr>
						{% endfor %}
						
						</tbody>

					</table>
					</div>


				</div>
			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->
{% endblock content %}

{% block javascript %}
{% endblock %}

customers/templates/customers/orders.html
{% extends 'customers/base.html' %}

{% block content %}
{% load humanize %}
<div class="content-wrap">
	<div class='main'>
	    <div class="page-header">
		<div class="page-title">
			<h1> Orders </h1>
		</div>
	    </div>

		<div class='containera-fluid'>
			<section id='main-content'>

				<div class='card'>
					<div class='card-body'>
						<div class='table-responsive'>

							<p>
							<a href='{% url "customers:order_create" %}'>
							<input type='button' id='checkout_btn' value='Create New Order' />
							</a>
							</p>

							<table class='table table-hover' id='myTable'>
								<thead>
									<tr>
										<th>Date</th>
										<th>Customer</th>
										<th>Quantity</th>
										<th>Shipping Fee</th>
										<th>Total</th>
										<th></th>
										<th></th>

									</tr>	
								</thead>
								<tbody> 
									{% for order in orders %}
									<tr>
										<td>{{ order.date }} </td>
										<td>
											<a href='{% url "customers:order_details" order.id %}'>
											{{ order.customer | title }}
											</a>
										</td>
										<td> {{ order.total_qty }}</td>
										<td> {{ order.shipping_fee| intcomma }}</td>
										<td> PHP {{ order.total_order | intcomma }}</td>
										<td>
											<a href='{% url "customers:order_update" order.id %}'>
											<i class='ti-pencil'></i>
											</a>
										</td>
										<td>
											<a href='{% url "customers:order_delete" order.id %}'>
											<i class='ti-trash'></i>
											</a>
										</td>


									</tr>
									{% endfor %}
								
								</tbody>

							</table>


						</div>	
					</div>
				</div>

			</section>
		</div>
		<!-- / container -->
	</div>
	<!-- /main -->
</div>
<!-- /content-wrap -->

{% endblock content %}